apiVersion: v1
kind: Service
metadata:
  name: {{ template "shadowsocks.fullname" . }}
  labels:
    app: {{ template "shadowsocks.name" . }}
    chart: {{ template "shadowsocks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
# kubernetes cannot expose UDP and TCP together
#{#{ if .Values.kcptun.enable }}
#    - port: {#{ .Values.kcptun.port }}
#      targetPort: 6500
#      protocol: UDP
#      name: kcptun
#{#{ else }}
    - port: {{ .Values.shadowsocks.port }}
      targetPort: 6443
      protocol: TCP
      name: shadowsocks
#{#{ end }}
  selector:
    app: {{ template "shadowsocks.name" . }}
    release: {{ .Release.Name }}
